[package]
name = "ntfy-client-gui-for-all-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "ntfy-client-gui-for-all-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ntfy-client-config = { path = "../config" }
ntfy-client-core = { path = "../core" }
ntfy-client-ipc = { path = "../ipc" }
ntfy-client-platform = { path = "../platform" }
ntfy-client-protocol = { path = "../protocol" }
secrecy.workspace = true
semver.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
